version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "@maw629"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "@maw629"
    allow:
      - dependency-type: "production"
    open-pull-requests-limit: 1
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
