# Funding options for @pkg-nec/http-server
#
# This file enables the "Sponsor" button in the GitHub repository.
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Buy Me a Coffee - Support the maintainer
buy_me_a_coffee: maw629
